
// // 1. Write a ts program to find length of a string.
// var a: string = "Hello World"
// console.log((`Length is :`), a.length);

// 2. Write a ts program to copy one string to another string.
// var x: string = "Hello World"
// var y: string = "Hello Sheraz"
// console.log(y);

// // 3. Write a ts program to concatenate two strings
// var b: string = "Hello"
// var c: string = "World"
// console.log((`Concatination:`), b + c);

// // 5. Write a ts program to convert lowercase string to uppercase.
// var d: string = "Hello World"
// console.log((`ToLowerCase:`), d.toLowerCase());

// // 6. Write a ts program to convert uppercase string to lowercase.
// var d: string = "Hello World"
// console.log((`To UpperCase:`), d.toUpperCase());

//14. Write a ts program to find first occurrence of a character in a given string.
// var x: string = "Pakistan"
// console.log(x.indexOf("a"))


//15. Write a ts program to find last occurrence of a character in a given string.
// var x: string = "Pakistan"
// console.log(x.lastIndexOf("a"))

//25. Write a ts program to replace first occurrence of a character with another in a string.
// var x: string = "Hello World"
// console.log(x.replace(`World`, `Pakistan`));

//26. Write a ts program to replace last occurrence of a character with another in a string.
// var x: string = "Hello World"
// console.log(x.replace(`Hello`, `Pakistan`));


//27. Write a ts program to replace all occurrences of a character with another in a string.
// var x: string = "Hello World"
// console.log(x.replaceAll("World", "Pakistan"));

// 28. Write a ts program to find first occurrence of a word in a given string.
// var x: string = "Hello World"
// console.log(x.indexOf(`Hello`));

// 29. Write a ts program to find last occurrence of a word in a given string.
// var x: string = "Hello World"
// console.log(x.lastIndexOf(`World`));


 // 38. Write a ts program to remove all extra blank spaces from given string.
 // var x: string = "                   Hello World                         "
 // console.log(x.trim());